"""Omnigent-shaped agent-definition export (P22 meta-harness-compat).

Omnigent (Databricks meta-harness, Apache 2.0) composes agents defined
via YAML plus a "common API pattern" over harnesses: a runner wraps
each agent, sessions run in pluggable sandboxes, and the server
persists sessions. Per ADR 0007 this repo composes UNDER Omnigent —
the assistant registers as an externally-served agent reachable over
its existing protocol surfaces (A2A card + JSON-RPC, MCP streamable
HTTP, AG-UI SSE) rather than as a CLI process Omnigent spawns.

HONESTY MARKER: this definition is designed from Omnigent's DOCUMENTED
concepts (YAML-defined agents, runner-wrapped sessions, pluggable
sandboxes; architecture review 2026-07-07 §6 links). The generating
environment could not fetch the omnigent-ai/omnigent repository, so
the exact schema is UNVERIFIED — the rendered file carries a header
telling the operator to verify field names against the canonical
schema on a connected machine before registering the agent.
"""

from __future__ import annotations

from importlib import metadata
from typing import Any

import yaml

from assistant.core.persona import PersonaConfig
from assistant.core.role import RoleConfig

#: Header prepended to every rendered definition. The "verify" wording
#: is load-bearing — see the module docstring.
UNVERIFIED_SCHEMA_HEADER = """\
# Omnigent-shaped agent definition — generated by
#   `assistant export-omnigent-agent` (P22 meta-harness-compat).
#
# VERIFY BEFORE USE: this file is Omnigent-SHAPED, designed offline
# from Omnigent's documented concepts (YAML-defined agents, runner
# wraps agent, sandboxed sessions, common API pattern). Verify field
# names/structure against the canonical omnigent-ai/omnigent schema on
# a connected machine before registering it — the generating
# environment could not fetch the schema (ADR 0007).
#
# Registration model: EXTERNAL/CUSTOM AGENT. Omnigent's runner should
# NOT spawn a CLI process for this agent; it composes via the served
# A2A / MCP / AG-UI endpoints below (`assistant serve -p <persona>
# --a2a --mcp`). See docs/deployment/meta-harness.md.
"""


def _package_version() -> str:
    try:
        return metadata.version("assistant")
    except metadata.PackageNotFoundError:  # pragma: no cover — editable envs
        return "0.0.0"


def build_omnigent_agent_definition(
    persona: PersonaConfig,
    roles: list[RoleConfig],
    *,
    base_url: str,
    version: str | None = None,
) -> dict[str, Any]:
    """Build the Omnigent-shaped agent definition as a plain dict.

    Content contract (meta-harness spec):

    - name/description from the persona;
    - endpoints for A2A (card + JSON-RPC), MCP (streamable HTTP, one
      ``ask_<role>`` tool per role plus generic ``ask``), and AG-UI
      (``/chat`` SSE + ``/health``), derived from ``base_url``;
    - auth declaration SHAPE from P25 ``auth.a2a`` (scheme + credential
      ref name only — never a token value);
    - one skill per enabled role (mirrors the A2A agent card).
    """
    base = base_url.rstrip("/")
    auth: dict[str, Any]
    if persona.a2a_auth is not None:
        auth = {
            "a2a": {
                "type": persona.a2a_auth.type,
                # Credential REF (env var / vault path name) — the
                # token itself is never exported.
                "token_env": persona.a2a_auth.token_env,
            }
        }
    else:
        auth = {
            "a2a": {
                "type": "none",
                "note": (
                    "loopback-unauthenticated; declare persona auth.a2a "
                    "(P25) before exposing beyond loopback"
                ),
            }
        }
    return {
        "kind": "external-agent",
        "name": persona.name,
        "display_name": persona.display_name or persona.name,
        "description": (
            f"agentic-assistant persona '{persona.name}' — persona/role/"
            f"capability layer composed under a meta-harness via its "
            f"served A2A/MCP/AG-UI endpoints (ADR 0007)."
        ),
        "version": version or _package_version(),
        "api": {
            "a2a": {
                "agent_card": f"{base}/.well-known/agent-card.json",
                "rpc": f"{base}/a2a/v1",
                "streaming": True,
            },
            "mcp": {
                "endpoint": f"{base}/mcp",
                "transport": "streamable-http",
                "tools": ["ask"] + [f"ask_{role.name}" for role in roles],
            },
            "ag_ui": {
                "chat": f"{base}/chat",
                "health": f"{base}/health",
                "protocol": "ag-ui/sse",
            },
        },
        "auth": auth,
        "skills": [
            {
                "id": role.name,
                "name": role.display_name or role.name,
                "description": role.description,
            }
            for role in roles
        ],
        "sandbox": {
            "managed_by": "assistant",
            "note": (
                "Sessions execute inside the assistant's own process "
                "behind the served endpoints; isolation is the persona "
                "'sandbox:' config (SandboxProvider seam), not an "
                "Omnigent-managed sandbox."
            ),
        },
        "x_generator": {
            "tool": "assistant export-omnigent-agent",
            "change": "meta-harness-compat (P22)",
            "schema_verified": False,
        },
    }


def render_omnigent_agent_yaml(definition: dict[str, Any]) -> str:
    """Render the definition as YAML with the unverified-schema header."""
    body = yaml.safe_dump(
        definition,
        sort_keys=False,
        default_flow_style=False,
        allow_unicode=True,
    )
    return UNVERIFIED_SCHEMA_HEADER + "\n" + body
